### PR TITLE
Provide a testing harness for apps

### LINKED ISSUE #535: Don't log to stderr in tests
In tests, we should log to the `testing.T` instead of standard error. Right now, when one test fails, the user is presented with *all* the output from *all* tests.

### PR DESCRIPTION
**Pull request by akshayjshah**
Currently, it's irritating for module owners to integration test their code - they have to use the plain `fx.App` type, which is a bit verbose for common test assertions. More importantly, `fx.App` writes verbose logs to standard error. Since Go's testing library buffers all console output and displays it when tests fail, this makes every test failure print a wall of Fx logs.

This PR exposes a `Logger` option that lets users replace an application's log destination, then adds an `fxtest.App` type that directs all output to the user's `testing.T`. Under this setup, test failures will only show the log output from that one test. Along the way, it adds `MustStart` and `MustStop` helpers.

Fixes #535.

### CODE REVIEW

File: internal/fxlog/fxlog.go [hunk 1]
```diff
@@ -32,28 +32,29 @@ import (
...
 // A Logger writes output to standard error.
 type Logger struct {
-	std printer
+	Printer
 }
 
 // Println logs a single Fx line.
 func (l *Logger) Println(str string) {
-	l.std.Printf(prepend(str))
+	l.Printer.Printf(prepend(str))
```
Comment (glibsm) [inline internal/fxlog/fxlog.go]: maybe just `l.Printf` here now that we embed?

File: fxtest/fxtest.go [hunk 2]
```diff
@@ -34,6 +36,50 @@ type TB interface {
...
+func (p *testPrinter) Printf(format string, args ...interface{}) {
+	p.Logf(format, args...)
+}
+
+// App is a wrapper around fx.App that provides some testing helpers. By
+// default, it uses the provided TB as the application's logging backend.
+type App struct {
+	*fx.App
+
+	tb TB
```
Comment (glibsm) [inline fxtest/fxtest.go]: is this meant to signal `testing.TB`?

File: app.go [hunk 3]
```diff
@@ -113,6 +113,20 @@ func Options(opts ...Option) Option {
 	})
 }
 
+// Printer is the interface required by fx's logging backend. It's implemented
+// by most loggers, including the standard library's.
```
Comment (glibsm) [inline app.go]: `(type *zap.Logger has no field or method Printf)`

If we wanted to use zap as an actual internal logger for the app as well, would we just build a bridge?

File: fxtest/fxtest.go [hunk 4]
```diff
@@ -34,6 +36,50 @@ type TB interface {
 	FailNow()
 }
 
+type testPrinter struct {
+	TB
```
Comment (abhinav) [inline fxtest/fxtest.go]: There's a TODO on `TB interface` that is resolved by this issue.

File: fxtest/fxtest.go [hunk 5]
```diff
@@ -34,6 +36,50 @@ type TB interface {
...
+// default, it uses the provided TB as the application's logging backend.
+type App struct {
+	*fx.App
+
+	tb TB
+}
+
+// New creates a new test application.
+func New(tb TB, opts ...fx.Option) *App {
+	allOpts := make([]fx.Option, 0, len(opts))
```
Comment (abhinav) [inline fxtest/fxtest.go]: nit: `len(opts) + 1`?

File: internal/fxlog/fxlog.go (hunk 1 above)
Comment (akshayjshah) [inline internal/fxlog/fxlog.go]: :+1: good point.

File: fxtest/fxtest.go (hunk 2 above)
Comment (akshayjshah) [inline fxtest/fxtest.go]: Yep, it's a subset of that interface. Depending on just a subset makes it easier to write a small testing spy, and it also avoids any chance of mistakenly compiling the testing package into production binaries.

File: app.go (hunk 3 above)
Comment (akshayjshah) [inline app.go]: `*zap.SugaredLogger` implements this interface.

File: internal/fxlog/fxlog.go (hunk 1 above)
Comment (akshayjshah) [inline internal/fxlog/fxlog.go]: Actually, it turns out that we just don't need this method at all.

File: fxtest/fxtest.go (hunk 4 above)
Comment (akshayjshah) [inline fxtest/fxtest.go]: :+1: good catch - fixed.
