### PR TITLE
Reuse local listener when starting http server

### LINKED ISSUE #365: Flaky http test
For Job https://travis-ci.org/uber-go/fx/jobs/207786565, logs:

2017/03/04 23:13:11 PASS | HTTPModule_StartsAndStops (0.00s)
2017/03/04 23:13:11 START| BuiltinHealth_OK
2017/03/04 23:13:11      | exit status 2
2017/03/04 23:13:11 FAIL | go.uber.org/fx/modules/uhttp  0.241s
2017/03/04 23:13:11      | {"level":"error","ts":1488669191.812442,"caller":"/tmp/go-build215164269/go.uber.org/fx/service/_test/_obj_test/manager.go:276","msg":"Failure to close tracer","error":"Failed to close","errorVerbose":"Failed to close\ngo.uber.org/fx/testutils.ErrorCloser.Close\n\tgo.uber.org/fx/testutils/metrics.go:40\ngo.uber.org/fx/testutils.(*ErrorCloser).Close\n\t<autogenerated>:2\ngo.uber.org/fx/service.(*manager).shutdown\n\t/tmp/go-build215164269/go.uber.org/fx/service/_test/_obj_test/manager.go:274\ngo.uber.org/fx/service.checkShutdown\n\tgo.uber.org/fx/service/manager_test.go:214\ngo.uber.org/fx/service.TestManagerShutdown_TracerCloserError\n\tgo.uber.org/fx/service/manager_test.go:209\ntesting.tRunner\n\t/home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:657\nruntime.goexit\n\t/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_amd64.s:2197","stacktrace":"goroutine 57 [running]:\ngo.uber.org/fx/vendor/go.uber.org/zap.takeStacktrace(0xc420428800, 0x800, 0x800, 0xd98400, 0x48, 0x0)\n\tgo.uber.org/fx/vendor/go.uber.org/zap/stacktrace.go:39 +0xe2\ngo.uber.org/fx/vendor/go.uber.org/zap.Stack(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\tgo.uber.org/fx/vendor/go.uber.org/zap/field.go:205 +0x9c\ngo.uber.org/fx/vendor/go.uber.org/zap.(*Logger).check(0xc420538660, 0x2, 0xad6785, 0x17, 0xc420434900)\n\tgo.uber.org/fx/vendor/go.uber.org/zap/logger.go:268 +0x300\ngo.uber.org/fx/vendor/go.uber.org/zap.(*Logger).Error(0xc420538660, 0xad6785, 0x17, 0xc420434900, 0x1, 0x1)\n\tgo.uber.org/fx/vendor/go.uber.org/zap/logger.go:176 +0x56\ngo.uber.org/fx/service.(*manager).shutdown(0xc4200a6c80, 0x0, 0x0, 0xacf1f5, 0x7, 0xc420605ec0, 0xdffb00, 0x0, 0x0)\n\t/tmp/go-build215164269/go.uber.org/fx/service/_test/_obj_test/manager.go:276 +0xc68\ngo.uber.org/fx/service.checkShutdown(0xc420517ba0, 0xc4200a6c80, 0xda8e01)\n\tgo.uber.org/fx/service/manager_test.go:214 +0x77\ngo.uber.org/fx/service.TestManagerShutdown_TracerCloserError(0xc420517ba0)\n\tgo.uber.org/fx/service/manager_test.go:209 +0x1af\ntesting.tRunner(0xc420517ba0, 0xb37ac0)\n\t/home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:657 +0x108\ncreated by testing.(*T).Run\n\t/home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:697 +0x544\n"}
2017/03/04 23:13:11 PASS | ManagerShutdown_TracerCloserError (0.00s)

Creating here, because I am working from my personal laptop.

### PR DESCRIPTION
**Pull request by alsamylkin**
We start server in a separate go routine, which may start execution after module is stopped. In this case listener will be nil and server will panic, which will cause our tests to fail. Before:
```
go test -run TestHTTPModule_StartsAndStops -count 50
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12bdd7f]

goroutine 162 [running]:
net/http.(*Server).Serve(0xc42008cfd0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2626 +0x4f
go.uber.org/fx/modules/uhttp.(*Module).Start.func1(0xc4205ca780)
	/Users/mortid0/go/src/go.uber.org/fx/modules/uhttp/http.go:160 +0xa2
created by go.uber.org/fx/modules/uhttp.(*Module).Start
	/Users/mortid0/go/src/go.uber.org/fx/modules/uhttp/http.go:163 +0x5d2
exit status 2
```

After:
```
go test -run TestHTTPModule_StartsAndStops -count 50000
PASS
ok  	go.uber.org/fx/modules/uhttp	6.760s
```

Fixes #365

### CODE REVIEW

**Comment by peter-edge** [comment]
This isn't actually necessary because of https://github.com/uber-go/fx/blob/master/service/module.go#L125. In terms of this isolated code, it is correct, however just pointing out this is covered for FX. I do like not assuming usage however (I think we might want to remove the documentation on service.Module that says "you can assume this will be called in a thread-safe manner).

**Comment by alsamylkin** [comment]
My main concern was a flaky test, that pointed this problem in our code: I had to manually restart a couple jobs for unrelated changes.

File: modules/uhttp/http.go [hunk 1]
```diff
@@ -152,6 +152,11 @@ func (m *Module) Start() error {
 		m.lock.RLock()
 		listener := m.listener
 		m.lock.RUnlock()
+		if listener == nil {
+			m.log.Error("listener is nil, module was stopped before server is able to start")
```
Comment (peter-edge) [inline modules/uhttp/http.go]: nit: I would not log here, I would return an error.

Comment (alsamylkin) [inline modules/uhttp/http.go]: hmm, this would require to change our tests :) Let me see what I can do.
